### PR TITLE
Add custom redirects

### PR DESCRIPTION
**Pull request by pettinarip**
## Description

This PR imports the custom redirects [we had in the main repo](https://github.com/ethereum/ethereum-org-website/blob/dev/redirects.json), using the Next syntax for redirects.

[Nextjs redirects doc](https://nextjs.org/docs/pages/api-reference/next-config-js/redirects)

## Related issue
https://www.notion.so/efdn/Add-redirects-06eacabd6bf54d1bb029aead70be70e8?pvs=4

### CODE REVIEW

**Review by wackerow — APPROVED** [review]
Should these be working within the Netlify preview? 

Looks good per the docs, and working locally with `yarn dev`, but they don't seem to be working within Netlify environment—just wanted to check... otherwise looks good

**Comment by corwintines** [comment]
Noticing this as well. Works locally, but not in Netlify. Would it be better to do this in _redirects which I think can go in the public folder https://docs.netlify.com/integrations/frameworks/next-js/redirects-and-rewrites/#app

**Comment by wackerow** [comment]
These still work when I run `netlify dev` just noting... not sure why the difference to the preview deploy

**Comment by pettinarip** [comment]
Thanks for the review @wackerow and @corwintines. True, I tested and got the same thing. Will investigate a bit more.

> Noticing this as well. Works locally, but not in Netlify. Would it be better to do this in _redirects which I think can go in the public folder https://docs.netlify.com/integrations/frameworks/next-js/redirects-and-rewrites/#app

Good call. Yeah, I guess we can go that route if I can't get it to work. My main reason for using the Next API was to use its redirect syntax, which plays really well with the i18n url nuances.

> These still work when I run `netlify dev` just noting... not sure why the difference to the preview deploy

Exactly, that was weird. I tested the build & serve with `netlify-cli` and it worked fine, but it doesn't seem to like the Netlify servers 🤷🏼

**Review by wackerow — COMMENTED** [review]
Nice, this appears to be working with a quick check... will test out a little more later on

**Review by wackerow — APPROVED** [review]
LGTM!

**Review by corwintines — APPROVED** [review]
LGTM. Just removed a few duplicates

**Pull request merged**
