### PR TITLE
feat:`/contributing/translation-program/acknowledgements/` page

### PR DESCRIPTION
**Pull request by nhsz**
This PR adds `/contributing/translation-program/acknowledgements/` page

## Description

- adds `/contributing/translation-program/acknowledgements/` page
- fixes `TranslationLeaderboard` translations
- removes `TranslationLeaderboard` component from `tsconfig` exclusion list

**Preview:** https://deploy-preview-189--ethereum-org-fork.netlify.app/contributing/translation-program/acknowledgements/

### CODE REVIEW

**Review by corwintines — APPROVED** [review]

**Review by pettinarip — COMMENTED** [review]
@nhsz noting a few differences with prod.

Maybe not related with this PR but I see that this banner is being displayed in the English path, but it shouldn't. And the page is translated in other languages.
image

=======

There is a missing margin or space between the nav and the content.

Current version:
image

Prod:
image

**Comment by nhsz** [comment]
> @nhsz noting a few differences with prod.
> 
> Maybe not related with this PR but I see that this banner is being displayed in the English path, but it shouldn't. And the page is translated in other languages. image
> 
> =======
> 
> There is a missing margin or space between the nav and the content.
> 
> Current version: image
> 
> Prod: image

@pettinarip Nav margins are broken in production for this page and fixed in this PR if you try navigating to  eg:`translation program`

The banner being displayed in the English path is a bug not related to this PR (its also appearing in other pages like `/contributing/translation-program`)

**Comment by pettinarip** [comment]
> @pettinarip Nav margins are broken in production for this page and fixed in this PR if you try navigating to eg:`translation program`
> 
> The banner being displayed in the English path is a bug not related to this PR (its also appearing in other pages like `/contributing/translation-program`)

Ah gotcha! gj!

**Review by pettinarip — APPROVED** [review]
Looks great!

**Pull request merged**
