### PR TITLE
Fix Algolia crawler DOM dependencies

### PR DESCRIPTION
**Pull request by wackerow**
## Description
- Implement `#main-content` throughout all layouts
- Re-enable `PageMetadata` in layouts 
- Remove old `Layout` component

## Related Issue
https://www.notion.so/efdn/Update-Algolia-crawler-script-2f5446ad14f04e8f9fc3c973adefe68f?pvs=4

### CODE REVIEW

**Review by pettinarip — APPROVED** [review]
Nice @wackerow we would need to use the same id on the rest of the pages that we are migrating, right?

**Comment by wackerow** [comment]
Good question. With this setup we would. Raises the question if we should do it this way... previously this was handled inside the `Layout` component, which would be `RootLayout` now.

We could consider wrapping the `{children}` within `RootLayout` in a div that contains this ID... Looks like this would actually be more aligned with parity of the canonical site.

The downside to the existing approach is the `#main-content` div includes all content from the page (everything between Nav and Footer basically), instead of just the main article, excluding any side navigation, etc.

Curious your thoughts/preferences here

**Comment by pettinarip** [comment]
@wackerow Hmm I think we want to target just the content. Couldn't we wrap the `children` with a new div with the id? https://github.com/ethereum/ethereum-org-fork/blob/dev/src/layouts/RootLayout.tsx#L62

**Comment by pettinarip** [comment]
> @wackerow Hmm I think we want to target just the content. Couldn't we wrap the `children` with a new div with the id? https://github.com/ethereum/ethereum-org-fork/blob/dev/src/layouts/RootLayout.tsx#L62

@wackerow maybe that doesn't work either because we want to also skip the page heros...I guess we need to do what you did here.

**Comment by wackerow** [comment]
@pettinarip 

> We could consider wrapping the {children} within RootLayout in a div that contains this ID

Yes, that was my thought for simplicity, but...

> I think we want to target just the content.

By doing this we'll also be including stuff like `SideNav` on the dev docs for example, and not specifically targeting just the content.

**Comment by pettinarip** [comment]
@wackerow converted the PR to a draft just to avoid merging it.

The PR looks good but we are going to wait until all the pages are migrated since we would like to implement this id on every page.

**Review by pettinarip — APPROVED** [review]
lgtm

**Pull request merged**
