### PR TITLE
Bump major node version to 20

### PR DESCRIPTION
**Pull request by wackerow**
## Description
Bump major node version to 20 on Netlify using `.nvmrc`

## Related issue
https://www.notion.so/efdn/Bump-node-version-f8bce8815ada42b1be24ff329514fc91?pvs=4

### CODE REVIEW

**Comment by wackerow** [comment]
Based on https://nodejs.org/en suggesting we bump our node version to latest recommended.

image

In Netlify deploy settings, we are not given the option for versions above 18:
image

[In the Netlify docs](https://docs.netlify.com/configure-builds/manage-dependencies/#node-js-and-javascript), they suggest using a `.nvmrc` file to declare this. Simply declaring the major version will override, which appears to be working in the logs for this PR:

```log
8:04:39 PM: Attempting Node.js version "20" from .nvmrc
8:04:39 PM: Downloading and installing node v20.9.0...
8:04:39 PM: Downloading https://nodejs.org/dist/v20.9.0/node-v20.9.0-linux-x64.tar.xz...
8:04:40 PM: Computing checksum with sha256sum
8:04:40 PM: Checksums matched!
8:04:42 PM: Now using node v20.9.0 (npm v10.1.0)
```

**Review by nhsz — COMMENTED** [review]
Does Netlify support Node 20.x? 🤔 We can maybe wait to update it before deploy (we have a `Before deploying to Prod` tag in Notion)

@wackerow On a sidenote, I'm still using LTS 18.x locally, have you tested if this works ok with current Next version? I remember having some build issues with newer versions

**Comment by wackerow** [comment]
So far so good, yeah... I realized yesterday that I had been using 20 this whole time locally.

I checked the logs of this PR, and Netlify loaded v20 without a problem and build to completion.

Happy to hold til before prod deployment (low priority overall), but it may be beneficial to not wait til last minute in case anything comes up. cc: @pettinarip

**Review by pettinarip — APPROVED** [review]
Since this is an LTS version (pretty sure that Netlify will update their UI soon) and it is working in both envs, I'm fine with merging it at this early stage to also test that everything goes well in this regard.

(tested locally and its working fine)

**Review by nhsz — APPROVED** [review]

**Pull request merged**
