### PR TITLE
Html direction update on locale change

### PR DESCRIPTION
**Pull request by wackerow**
## Description
A potential implementation to update the `dir` attribute for the `html` tag when the locale changes.
- `useEffect` hook used to refresh when dependency (`locale`) changes
- Extracted logic into `useLocaleDirection` hook
- Executed in `_app`; `_document` avoided as lifecycle hooks are not accessible
- Removed `direction` being passed to Chakra provider as this is no longer necessary

## Related Issue
https://www.notion.so/efdn/NextJS-general-QA-session-Dec-14th-cdec3085d96c4608a96b80772755f53a?pvs=4#18fdaf6f3a9748ffbbf9b69fad955cf6

Note: Don't love the usage of `document` here, but it works... thoughts from others?

### CODE REVIEW

**Review by pettinarip — COMMENTED** [review]
Good @wackerow, this is working fine now and I don't see any potential negative impact. Agreed that using `document` is not the best.

Curious about @TylerAPfledderer's thoughts about this patch.

**Comment by nhsz** [comment]
@wackerow @pettinarip seems it can be fixed [updating `_document` only](https://github.com/vercel/next.js/discussions/19049#discussioncomment-3343564)

**Comment by wackerow** [comment]
@nhsz So we're effectively already doing what is shown in that link:

image

...but this only runs once and doesn't update when the `locale` changes.

Only main difference I saw was they're using a functional component and we're using a class component, but switching this to a functional component locally didn't change anything.

This was why I tried approaching this with `_app` where we could use the `useEffect` hook to produce this side-effect when the route changes

**Review by corwintines — APPROVED** [review]

**Comment by wackerow** [comment]
Yeah, just tried this one last time using hooks within `_document` after refactoring to a functional component; still only running once and not updating when the locale changes... going to pull this PR in, and if we find an approach not using the `document` object we can update separately.

**Pull request merged**
